sdk:
  chipVerification:
    enabled: true
  rfid:
    pkdPaEnabled: false
    pkdPaPath: path
    paSensitiveCodes:
      - -1879048190
      - -1879048189

service:
  webServer:
    port: 8080
    workers: 4
    timeout: 30

    demoApp:
      enabled: true

    cors:
      origins: "*"
      headers: "Content-Type"
      methods: "POST,PUT,GET,DELETE,PATCH,HEAD"

    ssl:
      enabled: false
      cert: certs/tls.crt
      key: certs/tls.key
      tlsVersion: 1.2

    logging:
      level: DEBUG
      formatter: text

      access:
        console: true
        path: app/docreader-access.log

      app:
        console: true
        path: app/docreader-app.log

    metrics:
      enabled: true

  processing:
    enabled: true
    results:
      location:
        bucket: "docreader-processing"


  sessionApi:
    enabled: true
    mode: development
    saveRequest: true
    transactions:
      location:
        bucket: "docreader-transactions"


  storage:
    type: s3

    s3:
      accessKey: minioadmin
      accessSecret: minioadmin
      endpointUrl: http://s3-storage:9000
      region: eu-central-1
      secure: true

  database:
    connectionString: postgresql://regula:Regulapasswd#1@db-postgres:5432/regula_docreader_db
