global:
  scrape_interval: 10s

  external_labels:
    monitor: "docreader"

rule_files:

scrape_configs:
  - job_name: "docreader-monitoring"
    static_configs:
      - targets: ["docreader:8080"]

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: [ 'cadvisor:8080' ]

  - job_name: "locust-monitoring"
    static_configs:
      - targets: [ "127.0.0.1:9646" ]
