apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1


datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: b3a95192-0c55-4e25-8bb4-815fff10d074
    url: http://prometheus:9090
    editable: true
    isDefault: true