{
 "title": "Face API Prometheus metrics PROD",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Total Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(flask_http_request_duration_seconds_count{method=\"POST\", url_rule!~\"/api/ping|/api/readiness|/metrics\", status=~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule!~\"/api/ping|/api/readiness|/metrics\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule!~\"/api/ping|/api/readiness|/metrics\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule!~\"/api/ping|/api/readiness|/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{method=\"POST\", url_rule!~\"/api/ping|/api/readiness|/metrics\"}[$__rate_interval]))*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Detect Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\", url_rule=~\"/api/detect\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/detect\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/detect\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/detect\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p50,95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/detect\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95 {{url_rule}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/detect\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p50 {{url_rule}}"
    }
   ]
  },
  { "title": "Match Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\", url_rule=~\"/api/match\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/match\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/match\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/match\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p50,95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/match\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95 {{url_rule}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/match\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p50 {{url_rule}}"
    }
   ]
  },
  { "title": "Liveness v2 Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/v2/liveness.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status,url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/v2/liveness.*\",status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/v2/liveness.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/v2/liveness.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/v2/liveness.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95  {{url_rule}}"
    }
   ]
  },
  { "title": "Liveness v1 Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/liveness.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status,url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/liveness.*\",status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/liveness.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/liveness.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/liveness.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95  {{url_rule}}"
    }
   ]
  },
  { "title": "Old Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\", url_rule=~\"/api/matching.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    },
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\", url_rule=~\"/api/compare\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\", url_rule=\"/api/faces/sdk\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/matching.*\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/compare\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=\"/api/faces/sdk\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/matching.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/matching.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    },
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/compare\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/compare\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=\"/api/faces/sdk\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=\"/api/faces/sdk\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/matching.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95 {{url_rule}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/compare\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=\"/api/faces/sdk\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Search. Persons Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/persons.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status,url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/persons.*\",status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/persons.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/persons.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/persons.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95  {{url_rule}}"
    }
   ]
  },
  { "title": "Search. Group Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/group.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status,url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/group.*\",status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/group.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/group.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/group.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95  {{url_rule}}"
    }
   ]
  },
  { "title": "Search. Search Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/search.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    },
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/match_and_search.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status,url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/search.*\",status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}} {{url_rule}}"
    },
    {
     "expr": "sum by (status,url_rule) (rate(flask_http_request_duration_seconds_count{rl_rule=~\"/api/match_and_search.*\",status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/search.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/search.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    },
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{ethod=\"POST\",url_rule=~\"/api/match_and_search.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{ethod=\"POST\",url_rule=~\"/api/match_and_search.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/search.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95  {{url_rule}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{rl_rule=~\"/api/match_and_search.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"FaceR\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"FaceR\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"FaceR\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"FaceR\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "Milvus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"milvus\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"milvus\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"milvus\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"milvus\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"s3\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"s3\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"s3\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"s3\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  {
   "title": "SQL liveness transaction repository",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 }
  },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"sql_liveness_transaction_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"sql_liveness_transaction_repository\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"sql_liveness_transaction_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"sql_liveness_transaction_repository\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "SQL person repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"sql_person_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"sql_person_repo\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"sql_person_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"sql_person_repo\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "SQL group repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"sql_group_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"sql_group_repo\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"sql_group_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"sql_group_repo\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "SQL image repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"sql_image_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"sql_image_repo\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"sql_image_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"sql_image_repo\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "SQL audit repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"sql_audit_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"sql_audit_repository\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"sql_audit_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"sql_audit_repository\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  }
 ]
}