{
 "title": "Face API Prometheus Dashboard (Grouped)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rate_interval", "query": "30s,1m" }
  ]
 },
 "panels": [
  { "title": "GPU Nvidia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "GPU {{gpu}}" }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Power total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(DCGM_FI_DEV_POWER_USAGE{})", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "quantile(0.95, 100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(name) (\n rate(container_cpu_usage_seconds_total[$__rate_interval])\n)  \n/ scalar(machine_cpu_cores)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (name) (container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{status=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{status=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Request Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Compare API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/faces.*\", method !=\"OPTIONS\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    },
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/matching.*\", method !=\"OPTIONS\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    },
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=\"/api/compare\", method !=\"OPTIONS\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    },
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=\"/api/match\", method !=\"OPTIONS\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Detect API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 41 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/detect.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Liveness API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/liveness.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Liveness V2 API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/v2/liveness.*\", method !=\"OPTIONS\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Group API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{url_rule=\"/api/groups\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/groups"
    },
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{url_rule=\"/api/groups\", method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "POST /api/groups"
    },
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/groups/.*\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/groups/<group_id>"
    },
    {
     "expr": "sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/groups/.*\", method=\"DELETE\"}[$__rate_interval]))",
     "legendFormat": "DELETE /api/groups/<group_id>"
    },
    {
     "expr": "sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/groups\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/persons/<person_id>/groups"
    },
    {
     "expr": "sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/groups/.*/persons\", method=\"PUT\"}[$__rate_interval]))",
     "legendFormat": "PUT /api/groups/<group_id>/persons"
    },
    {
     "expr": "sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/groups\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/persons/<person_id>/groups"
    }
   ]
  },
  {
   "title": "Compare API Endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by (url_rule, method) (increase(flask_http_request_duration_seconds_sum{url_rule=~\"/api/faces.*\", method !=\"OPTIONS\"}[$__rate_interval])) / sum by (url_rule, method) (increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/faces.*\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    },
    {
     "expr": "sum by (url_rule, method) (increase(flask_http_request_duration_seconds_sum{url_rule=~\"/api/matching.*\", method !=\"OPTIONS\"}[$__rate_interval])) / sum by (url_rule, method) (increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/matching.*\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    },
    {
     "expr": "sum by (url_rule, method) (increase(flask_http_request_duration_seconds_sum{url_rule=\"/api/compare\", method !=\"OPTIONS\"}[$__rate_interval])) / sum by (url_rule, method) (increase(flask_http_request_duration_seconds_count{url_rule=\"/api/compare\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    },
    {
     "expr": "sum by (url_rule, method) (increase(flask_http_request_duration_seconds_sum{url_rule=\"/api/match\", method !=\"OPTIONS\"}[$__rate_interval])) / sum by (url_rule, method) (increase(flask_http_request_duration_seconds_count{url_rule=\"/api/match\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Detect API Endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 49 },
   "targets": [
    {
     "expr": "sum by (url_rule, method) (increase(flask_http_request_duration_seconds_sum{url_rule=~\"/api/detect.*\", method !=\"OPTIONS\"}[$__rate_interval])) / sum by (url_rule, method) (increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/detect.*\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Liveness API Endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "sum by (url_rule, method) (increase(flask_http_request_duration_seconds_sum{url_rule=~\"/api/liveness.*\"}[$__rate_interval])) / sum by (url_rule, method) (increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/liveness.*\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Liveness V2 API Endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum by (url_rule, method) (increase(flask_http_request_duration_seconds_sum{url_rule=~\"/api/v2/liveness.*\", method !=\"OPTIONS\"}[$__rate_interval])) / sum by (url_rule, method) (increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/v2/liveness.*\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Group API Endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "sum by (status) (increase(flask_http_request_duration_seconds_sum{url_rule=\"/api/groups\", method=\"GET\"}[$__rate_interval])) / sum by (status) (increase(flask_http_request_duration_seconds_count{url_rule=\"/api/groups\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/groups"
    },
    {
     "expr": "sum by (status) (increase(flask_http_request_duration_seconds_sum{url_rule=\"/api/groups\", method=\"POST\"}[$__rate_interval])) / sum by (status) (increase(flask_http_request_duration_seconds_count{url_rule=\"/api/groups\", method=\"POST\"}[$__rate_interval])) * 1000",
     "legendFormat": "POST /api/groups"
    },
    {
     "expr": "sum by (status) (increase(flask_http_request_duration_seconds_sum{url_rule=~\"/api/groups/.*\", method=\"GET\"}[$__rate_interval])) / sum by (status) (increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/groups/.*\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/groups/<group_id>"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/groups/.*\", method=\"DELETE\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/groups/.*\", method=\"DELETE\"}[$__rate_interval])) * 1000",
     "legendFormat": "DELETE /api/groups/<group_id>"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/groups\", method=\"GET\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/groups\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/persons/<person_id>/groups"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/groups/.*/persons\", method=\"PUT\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/groups/.*/persons\", method=\"PUT\"}[$__rate_interval])) * 1000",
     "legendFormat": "PUT /api/groups/<group_id>/persons"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/groups\", method=\"GET\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/groups\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/persons/<person_id>/groups"
    }
   ]
  },
  {
   "title": "Search API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/.*search.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Person API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 57 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(rate(flask_http_request_duration_seconds_count{url_rule=\"/api/persons\", method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "GET /api/persons"
    },
    {
     "expr": "sum by(url_rule, method)(rate(flask_http_request_duration_seconds_count{url_rule=\"/api/persons\", method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "POST /api/persons"
    },
    {
     "expr": "sum by(url_rule, method)(rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images\", method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "POST /api/persons/<person_id>/images"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images/.*\", method=\"DELETE\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images/.*\", method=\"DELETE\"}[$__rate_interval])) * 1000",
     "legendFormat": "DELETE /api/persons/<person_id>/images/<image_id>"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images/sdk\", method=\"POST\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images/sdk\", method=\"POST\"}[$__rate_interval])) * 1000",
     "legendFormat": "POST /api/persons/<person_id>/images/sdk"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*\", method=\"PUT\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*\", method=\"PUT\"}[$__rate_interval])) * 1000",
     "legendFormat": "PUT /api/persons/<person_id>"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images\", method=\"GET\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/persons/<person_id>/images"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images/.*\", method=\"GET\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images/.*\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/persons/<person_id>/images/<image_id>"
    },
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*\", method=\"DELETE\"}[$__rate_interval])) / sum by (status) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*\", method=\"DELETE\"}[$__rate_interval])) * 1000",
     "legendFormat": "DELETE /api/persons/<person_id>/"
    }
   ]
  },
  {
   "title": "sql_person_repo  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "sum by (operation)(increase(func_request_time_sum{service=\"sql_person_repo\"}[$__rate_interval])) / sum by (operation)(rate(func_request_time_count{service=\"sql_person_repo\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_group_repo  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"sql_group_repo\"}[$__rate_interval])) / sum  by(operation)(increase(func_request_time_count{service=\"sql_group_repo\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Search API Endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (url_rule, method) (rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/.*search.*\"}[$__rate_interval])) / sum by (url_rule, method) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/.*search.*\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Person API Endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 65 },
   "targets": [
    {
     "expr": "sum (rate(flask_http_request_duration_seconds_sum{url_rule=\"/api/persons\", method=\"GET\"}[$__rate_interval])) / sum(rate(flask_http_request_duration_seconds_count{url_rule=\"/api/persons\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/persons"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=\"/api/persons\", method=\"POST\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=\"/api/persons\", method=\"POST\"}[$__rate_interval])) * 1000",
     "legendFormat": "POST /api/persons"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images\", method=\"POST\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images\", method=\"POST\"}[$__rate_interval])) * 1000",
     "legendFormat": "POST /api/persons/<person_id>/images"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images/.*\", method=\"DELETE\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images/.*\", method=\"DELETE\"}[$__rate_interval])) * 1000",
     "legendFormat": "DELETE /api/persons/<person_id>/images/<image_id>"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images/sdk\", method=\"POST\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images/sdk\", method=\"POST\"}[$__rate_interval])) * 1000",
     "legendFormat": "POST /api/persons/<person_id>/images/sdk"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*\", method=\"PUT\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*\", method=\"PUT\"}[$__rate_interval])) * 1000",
     "legendFormat": "PUT /api/persons/<person_id>"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images\", method=\"GET\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/persons/<person_id>/images"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*/images/.*\", method=\"GET\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*/images/.*\", method=\"GET\"}[$__rate_interval])) * 1000",
     "legendFormat": "GET /api/persons/<person_id>/images/<image_id>"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{url_rule=~\"/api/persons/.*\", method=\"DELETE\"}[$__rate_interval])) / sum (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/persons/.*\", method=\"DELETE\"}[$__rate_interval])) * 1000",
     "legendFormat": "DELETE /api/persons/<person_id>/"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(increase(func_counter_total{service=~\"sql_.*\"}[$__rate_interval]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "sql_person_repo count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 73 },
   "targets": [
    {
     "expr": "sum by (operation)(increase(func_counter_total{service=\"sql_person_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_group_repo count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"sql_group_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_liveness_transaction_repo count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"sql_liveness_transaction_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_image_repo count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 79 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"sql_image_repo\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_person_repo p95  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 79 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"sql_person_repo\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_group_repo p95  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"sql_group_repo\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_liveness_transaction_repository  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"sql_liveness_transaction_repository\"}[$__rate_interval])) / sum by(operation)(increase(func_request_time_count{service=\"sql_liveness_transaction_repository\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_image_repo (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 85 },
   "targets": [
    {
     "expr": "sum by(operation)(rate(func_request_time_sum{service=\"sql_image_repo\"}[$__rate_interval])) / sum by(operation)(rate(func_request_time_count{service=\"sql_image_repo\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_liveness_transaction_repository p95  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 85 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"sql_liveness_transaction_repository\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_image_repo p95  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"sql_image_repo\"}[$__rate_interval]))) *1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Milvus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Milvus count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"milvus\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(increase(func_counter_total{service=\"milvus\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Milvus request time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"milvus\"}[$__rate_interval])) / sum by(operation)(increase(func_request_time_count{service=\"milvus\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Milvus p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"milvus\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "FaceR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "FaceR count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"FaceR\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(increase(func_counter_total{service=\"FaceR\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "FaceR p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"FaceR\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "FaceR request time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"FaceR\"}[$__rate_interval])) / sum by(operation)(increase(func_request_time_count{service=\"FaceR\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "S3 request time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"S3\"}[$__rate_interval])) / sum by(operation)(increase(func_request_time_count{service=\"S3\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "S3 count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 110 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"S3\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(increase(func_counter_total{service=\"S3\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "S3 p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 110 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"S3\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}