{
 "title": "Docreader Prometheus metrics (PROD)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Total Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(flask_http_request_duration_seconds_count{ method=\"POST\", url_rule!~\"/api/ping|/api/readiness|/metrics\", status=~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{ url_rule!~\"/api/ping|/api/readiness|/metrics\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{method=\"POST\",url_rule!~\"/api/ping|/api/readiness|/metrics\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\",url_rule!~\"/api/ping|/api/readiness|/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{ method=\"POST\", url_rule!~\"/api/ping|/api/readiness|/metrics\"}[$__rate_interval]))*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Process Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{ url_rule=\"/api/process\", status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{method=\"POST\",url_rule=~\"/api/process\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\",url_rule=~\"/api/process\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p50,95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{url_rule=~\"/api/process\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95 {{url_rule}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{url_rule=~\"/api/process\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p50 {{url_rule}}"
    }
   ]
  },
  { "title": "Session API Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/v2.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (status,url_rule) (rate(flask_http_request_duration_seconds_count{url_rule=~\"/api/v2.*\",status!~\"20.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (url_rule) (rate(flask_http_request_duration_seconds_sum{method=\"POST\",url_rule=~\"/api/v2.*\"}[$__rate_interval])) / sum by (url_rule) (rate(flask_http_request_duration_seconds_count{method=\"POST\",url_rule=~\"/api/v2.*\"}[$__rate_interval]))",
     "legendFormat": "{{url_rule}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (url_rule, le) (rate(flask_http_request_duration_seconds_bucket{url_rule=~\"/api/v2.*\",method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "p95  {{url_rule}}"
    }
   ]
  },
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"docreader_core\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"docreader_core\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"docreader_core\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"docreader_core\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"$storage_type\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"$storage_type\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"$storage_type\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"$storage_type\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"transaction_service\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"transaction_service\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"transaction_service\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"transaction_service\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "SQL transaction repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"sql_transaction_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"sql_transaction_repository\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"sql_transaction_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"sql_transaction_repository\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  {
   "title": "Request per second (Reproc)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"sql_reproc_trans_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time (Reproc)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"sql_reproc_trans_repository\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"sql_reproc_trans_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95 (Reproc)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"sql_reproc_trans_repository\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  { "title": "Image download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_count{service=\"image_download_service\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(func_request_time_sum{service=\"image_download_service\"}[$__rate_interval])) / sum by (operation) (rate(func_request_time_count{service=\"image_download_service\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(func_request_time_histogram_bucket{service=\"image_download_service\"}[$__rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  }
 ]
}