{
 "title": "Docreader Prometheus Dashboard (Grouped)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rate_interval", "query": "30s,1m" }
  ]
 },
 "panels": [
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "quantile(0.95, 100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(name) (\n rate(container_cpu_usage_seconds_total[$__rate_interval])\n)  \n/ scalar(machine_cpu_cores)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (name) (container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{status=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{status=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum (increase(flask_http_request_duration_seconds_count{status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Request Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Session API Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/v2.*\", method !=\"OPTIONS\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "Process Endpoints (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
   "targets": [
    {
     "expr": "sum by(url_rule, method)(increase(flask_http_request_duration_seconds_count{url_rule=~\"/api/process\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{url_rule}}"
    }
   ]
  },
  {
   "title": "sql_reproc_trans_repository  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum by (operation)(increase(func_request_time_sum{service=\"sql_reproc_trans_repository\"}[$__rate_interval])) / sum by (operation)(rate(func_request_time_count{service=\"sql_reproc_trans_repository\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_transaction_repository  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"sql_transaction_repository\"}[$__rate_interval])) / sum  by(operation)(increase(func_request_time_count{service=\"sql_transaction_repository\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(func_counter_total{service=~\"sql_.*\"}[$__rate_interval]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "sql_reproc_trans_repository count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum by (operation)(increase(func_counter_total{service=\"sql_reproc_trans_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_transaction_repository count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"sql_transaction_repository\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_reproc_trans_repository  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"sql_reproc_trans_repository\"}[$__rate_interval])) / sum by(operation)(increase(func_request_time_count{service=\"sql_reproc_trans_repository\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_transaction_repository (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 35 },
   "targets": [
    {
     "expr": "sum by(operation)(rate(func_request_time_sum{service=\"sql_transaction_repository\"}[$__rate_interval])) / sum by(operation)(rate(func_request_time_count{service=\"sql_transaction_repository\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_reproc_trans_repository p95  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"sql_reproc_trans_repository\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "sql_transaction_repository p95  (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"sql_transaction_repository\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "ProcMgrDocumentReaderCore count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"docreader_core\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(increase(func_counter_total{service=\"docreader_core\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "ProcMgrDocumentReaderCore p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"docreader_core\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "ProcMgrDocumentReaderCore request time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"docreader_core\"}[$__rate_interval])) / sum by(operation)(increase(func_request_time_count{service=\"docreader_core\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "S3 request time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_request_time_sum{service=\"S3\"}[$__rate_interval])) / sum by(operation)(increase(func_request_time_count{service=\"S3\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "S3 count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "sum by(operation)(increase(func_counter_total{service=\"S3\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(increase(func_counter_total{service=\"S3\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "S3 p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (increase(func_request_time_histogram_bucket{service=\"S3\"}[$__rate_interval]))) * 1000",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}