global:
  scrape_interval: 10s

  external_labels:
    monitor: "face-api"

rule_files:

scrape_configs:
  - job_name: "face-api-monitoring"
    static_configs:
      - targets: ["faceapi:41101"]

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: [ 'cadvisor:8080' ]
