name: Trivy Scan

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scaner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          skip-dirs: 'deployment/certs'
